version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  myapp:
    build: .

  parca:
    image: ghcr.io/parca-dev/parca:v0.22.0
    ports:
      - "7070:7070"
    volumes:
      - type: bind
        source: ./parca.yaml
        target: /parca.yaml
    entrypoint: ["ls -la /"]

  parca-agent:
    image: ghcr.io/parca-dev/parca-agent:v0.32.0
    privileged: true
    command: --log-level=debug --node=binary-test --remote-store-address=localhost:7070 --remote-store-insecure
    depends_on:
      - parca

volumes:
  grafana_data: